- id: scieqlint
  name: SciEqLint
  description: Check equations and equation references in supported scientific documents.
  entry: scieqlint check
  language: python
  files: '\.(md|markdown|tex|ipynb)$'
  require_serial: true
